#MAINTAINER https://github.com/airdb

FROM ubuntu:20.04

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
RUN echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile

RUN echo "export PS1='[\H \W]\\$ '" >> /root/.profile
