version: '3'

services:
  toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'airdb/toolbox:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/
    ports:
      - "8080:8080"
    environment:
      - env=test
    container_name: toolbox
