version: '3'

services:
  toolbox:
    #platform: linux/amd64
    build:
      context: ../
      # dockerfile: ./dockerfile/Dockerfile.alpine.toolbox
      dockerfile: ./dockerfile/Dockerfile.ubuntu.base
    image: 'airdb/toolbox:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/toolbox
    ports:
      - "8080:8080"
    environment:
      - env=test
    container_name: toolbox
