version: '3'

services:
  wsgi:
    container_name: wsgi
    platform: linux/amd64
    image: 'airdb/wsgi:latest'
    working_dir: /app/wsgi
    build:
      context: .
      dockerfile: Dockerfile
        #command: sleep 3600
    volumes:
      - ./:/app/wsgi/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - env=test
