FROM golang:1.23.0

LABEL maintainer="airdb team <info@airdb.com>"
LABEL description="https://github.com/airdb"

RUN cp /usr/share/zoneinfo/Asia/Singapore /etc/localtime

WORKDIR /srv

CMD ["/bin/bash", "--login"]
