version: '3'

services:
  toolbox:
    container_name: ubuntu
    working_dir: /srv/
    build:
      context: .
      dockerfile: Dockerfile
    image: 'airdb/ubuntu:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/ubuntu
    ports:
      - "8080:8080"
    environment:
      - env=test
