version: '3.3'
services:
  builder:
    container_name: builder
    image: 'airdb/builder:debian-go1.18'
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    environment:
      - env=test
