version: '3'

services:
  alpine:
    container_name: alpine
      #platform: linux/amd64
    working_dir: /srv/
    build:
      context: .
      dockerfile: Dockerfile
    image: 'airdb/alpine:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/alpine
    ports:
      - "8080:8080"
    environment:
      - env=test
