services:
  squid:
    container_name: squid
    image: "airdb/squid:latest"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    network_mode: host
    volumes:
      - ./:/srv/proxy
    environment:
      - env=test
