services:
  dotnet:
    container_name: dotnet
    image: "airdb/dotnet:latest"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    volumes:
      - ./:/srv/dotnet
    ports:
      - "8080:8080"
    environment:
      - env=test
