
version: '2.0'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:80
    container_name: nginx
