services:
  apkbuild:
    container_name: apkbuild
    image: "airdb/apkbuild:latest"
    platform: linux/amd64
    working_dir: /srv/
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    volumes:
      - ./:/srv/apkbuild
    ports:
      - "8080:8080"
    environment:
      - env=test
