version: '3.8'

services:
  testdb8:
    container_name: testdb8
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password --init-file /srv/sql/init.sql
    volumes:
      - ./:/srv/sql/
        #network_mode: "host"
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: airdb
      MYSQL_PASSWORD: airdb
