FROM node
MAINTAINER https://github.com/airdb

ENV DEBIAN_FRONTEND noninteractive
WORKDIR /srv

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

ENV RUNNING_CONTEXT "docker"
ENV echo "export RUNNING_CONTEXT=docker" >> /etc/profile

RUN echo "export PS1='[\H \W]\\$ '" >> /root/.profile

# curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
# npm install -g @d2-admin/d2-admin-cli
RUN apt update && \
	apt install -y curl git vim
