services:
  golang:
    container_name: golang
    image: "airdb/golang:latest"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    volumes:
      - ./:/srv/toolbox
    ports:
      - "8080:8080"
    environment:
      - env=test
