version: '3.9'
services:
  builder:
    container_name: builder
    image: 'airdb/builder:alpine-go1.21'
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    environment:
      - env=test
