version: '3'

services:
  python:
    container_name: python
    platform: linux/amd64
    working_dir: /srv/
    build:
      context: .
      dockerfile: Dockerfile
    image: 'airdb/python:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/python
    ports:
      - "8080:8080"
    environment:
      - env=test
