version: '3'

services:
  nodejs:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./dockerfile/Dockerfile.ubuntu.nodejs
    image: 'airdb/nodejs:latest'
    command: sleep 3600
    volumes:
      - ./:/srv/toolbox
    ports:
      - "8080:9090"
    environment:
      - env=test
    container_name: nodejs
