version: '3'

services:
  nodejs:
    container_name: nodejs
    image: 'airdb/nodejs:latest'
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    volumes:
      - ./:/srv/toolbox
    ports:
      - "8080:9090"
    environment:
      - env=test
