up:
	sudo docker-compose up -d --build --force-recreate
build:
	sudo docker-compose build

start:
	sudo docker-compose start

stop:
	sudo docker-compose stop

restart:
	sudo docker-compose restart

ps:
	sudo docker-compose ps

bash:
	sudo docker-compose exec testdb5 bash

logs:
	sudo docker-compose logs