version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #ports:
    #  - '5432:5432'
    volumes: 
      - pgsql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgsql:
    driver: local
