version: '3.9'
services:
  buf:
    container_name: buf
    image: 'airdb/buf:latest'
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    environment:
      - env=test
