services:
  base:
    container_name: base
    image: "airdb/base:latest"
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    environment:
      - env=test
      - TZ=Asia/Shanghai
