services:
  python:
    container_name: python
    platform: linux/amd64
    image: "airdb/python:latest"
    working_dir: /app/python
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 3600
    volumes:
      - ./:/srv/ubuntu
    ports:
      - "8000:8000"
    environment:
      - env=test
