version: '3'

services:
  testdb8:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password --init-file /srv/sql/init.sql
    volumes:
      - ./:/srv/sql/
        #network_mode: "host"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=airdb
      - MYSQL_PASSWORD=airdb
    container_name: testdb8
