up:
	docker compose up -d --build --force-recreate
build:
	docker compose build

start:
	docker compose start

stop:
	docker compose stop

restart:
	docker compose restart

ps:
	docker compose ps

bash:
	docker compose exec testdb8 bash

logs:
	docker compose logs